### ISSUE TITLE
Output code isn't async

### ISSUE THREAD

**Issue by jakereps** [shinnn/isogram#19]
The README has the most current version of the code block, but the actual output of the app doesn't match. It still uses an older format, and isn't the newer (as of 2015) async version. 

I might be able to mess around with updating this, if that's cool?

**Comment by shinnn** [comment]
The output code is actually *async*.

https://mathiasbynens.be/notes/async-analytics-snippet#async

> all dynamically inserted `<script>`s default to `.async=true` [as per the spec](https://html.spec.whatwg.org/multipage/scripting.html).

**Comment by jakereps** [comment]
Huh, interesting. I wonder why Google decided to add it then. They even provided an entirely rewritten version specifically for [async preloading](https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tracking_snippet):

```javascript
<!-- Google Analytics -->
<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-XXXXX-Y', 'auto');
ga('send', 'pageview');
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
<!-- End Google Analytics -->
```

**Comment by shinnn** [comment]
Here is not a Google Analytics issue tracker but just one npm module's.
